plugin:
    name: 'ipricegroup.ocapiplugin::lang.plugin.name'
    description: 'ipricegroup.ocapiplugin::lang.plugin.description'
    author: 'iPrice Group'
    icon: icon-cloud
    homepage: 'https://iprice.my'
navigation:
    iprice-api-main:
        label: 'iPrice API'
        url: /ipricegroup/ocapiplugin/resources
        icon: icon-cloud
